# Create a new pod nginx-4 with nginx image 
# and mount the secret db-secret-1 as a volume named db-secret and mount path /secret

apiVersion: v1
kind: Pod
metadata:
  name: nginx-4
spec:
  containers:
    - image: nginx
      name: nginx-4
      volumeMounts:
        - name: db-secret
          mountPath: "/secret"
          readOnly: true
  volumes:
    - name: db-secret
      secret:
        secretName: db-secret-1

---

apiVersion: v1
kind: Secret
metadata:
  name: db-secret-1
stringData:
  secretKey: BASE64_ENCODED_VALUE
type: Opaque
