apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: canary-app
        image: httpd:2.4