apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front-end
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - image: nginx:1.202.33333 # Update the image
        name: nginx-deployment