# Name: nginx-random using the nginx image
# Exposed via a service nginx-random
# Ensure that the service & pod are accessible via their respective DNS records
# Use the utility nslookup to lookup the DNS records of the service & pod

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-random
spec:
  selector:
    matchLabels:
      app: random
  template:
    metadata:
      labels:
        app: random
    spec:
      containers:
      - name: nginx-random
        image: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-random
spec:
  selector:
    app: random
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
spec:
  containers:
  - name: dnsutils
    image: busybox:1.28.0
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always