apiVersion: batch/v1
kind: CronJob
metadata:
  name: time-limited-job
spec:
  schedule: '* * * * *'
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300 # add this line
      template:
        spec:
          containers:
          - args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            image: busybox
            name: time-limited-job
          restartPolicy: Never
  
#설정된 시간에 도달하면 잡은 죽는다