apiVersion: batch/v1
kind: Job
metadata:
  name:  busybox-job
spec:
  completions: 5
  parallelism: 5
  template:
    metadata:
      name:  busybox
    spec:
      containers:
        - name: busybox
          image: busybox
      restartPolicy: Never